module.exports = {
    apps: [{
        name: 'hotbando-api',
        script: 'index.js',
        instances: process.env.NODE_ENV === 'production' ? 2 : 1,
        exec_mode: 'cluster',
        watch: process.env.NODE_ENV !== 'production',
        ignore_watch: ['node_modules', 'logs', 'public/uploads'],
        max_memory_restart: '512M',
        env: {
            NODE_ENV: 'development',
            PORT: 3000,
        },
        env_production: {
            NODE_ENV: 'production',
            PORT: 3000,
        },
        error_file: 'logs/err.log',
        out_file: 'logs/out.log',
        log_file: 'logs/combined.log',
        time: true,
        log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        merge_logs: true,
        max_restarts: 10,
        restart_delay: 5000,
        listen_timeout: 3000,
        kill_timeout: 5000,
        shutdown_with_message: true,
    }],
};
